name: cd-workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'false'
        
    - name: Pull docker image from Amazon ECR
      env:
        REGISTRY: 211125733929.dkr.ecr.us-east-1.amazonaws.com
        REPOSITORY: object_detection_repo
        IMAGE_TAG: latest
      run: |
        sudo docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
        
    - name: Delete old container if exists
      run: sudo docker rm -f object-detection || true
      
    - name: Run new container
      env:
        REGISTRY: 211125733929.dkr.ecr.us-east-1.amazonaws.com
        REPOSITORY: object_detection_repo
        IMAGE_TAG: latest
      run: |
        sudo docker run -d -p 8501:8501 --name object-detection $REGISTRY/$REPOSITORY:$IMAGE_TAG
